apiVersion: v1
kind: Service
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
spec:
  selector:
    app: {{ k8s_name }}
  ports:
    - port: {{ db_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ db_metrics_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  clusterIP: None