apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 40.3.1
  targetNamespace: "{{ namespace }}"
  valuesContent: |-
    grafana:
      ## Configure additional grafana datasources (passed through tpl)
      ## ref: http://docs.grafana.org/administration/provisioning/#datasources
      additionalDataSources:
        - name: Loki
          type: loki
          isDefault: false
          access: proxy
          url: http://loki-stack.monitoring:3100
          version: 1

      grafana.ini:
        auth.anonymous:
          enabled: true
        server:
          domain: {{ hostname }}
          root_url: https://{{ hostname }}/grafana/
          serve_from_sub_path: true
  