apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-route
  namespace: "{{ namespace }}"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/traefik`) || HeadersRegexp(`Referer`, `.*/traefik/.*`)
      middlewares:
        - name: "{{ auth_middelware_name }}"
          namespace: "{{ auth_middelware_namespace }}"
        - name: "{{ name }}-traefik-redirect"
          namespace: "{{ namespace }}"
        - name: "{{ name }}-traefik-stripprefix"
          namespace: "{{ namespace }}"
      services:
        - kind: Service
          name: traefik
          namespace: kube-system
          port: traefik