- name: Create folder for temp SSH Key
  ansible.builtin.file:
    path: /tmp/.ssh
    state: directory
    mode: 0777
  delegate_to: localhost
- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: /tmp/.ssh/id_ed25519
    type: ed25519
    state: present
    mode: 0600
  delegate_to: localhost
- name: Create folder for target SSH Key
  ansible.builtin.file:
    path: "{{ private_key_file | dirname }}"
    state: directory
    mode: 0777
  delegate_to: localhost
- name: Copy SSH private key
  ansible.builtin.copy:
    src: /tmp/.ssh/id_ed25519
    dest: "{{ private_key_file }}"
    mode: 0600
  delegate_to: localhost
- name: Copy SSH public key
  ansible.builtin.copy:
    src: /tmp/.ssh/id_ed25519.pub
    dest: "{{ private_key_file }}.pub"
    mode: 0600
  delegate_to: localhost
- name: Create deploy user
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    password: "{{ password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    groups: sudo
    append: true
  vars:
    password: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname) }}"
- name: Enable SSH key auth
  become: true
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', public_key_file) }}"
  vars:
    public_key_file: "{{ private_key_file }}.pub"
