- name: Deploy Kube Prometheus Stack
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    chart_ref: kube-prometheus-stack
    chart_version: 40.3.1
    wait: true
    release_namespace: monitoring
    release_values:
      grafana:
        ## Configure additional grafana datasources (passed through tpl)
        ## ref: http://docs.grafana.org/administration/provisioning/#datasources
        additionalDataSources:
          - name: Loki
            type: loki
            isDefault: false
            access: proxy
            url: http://loki-stack.monitoring:3100
            version: 1

        grafana.ini:
          auth.anonymous:
            enabled: true
          server:
            domain: "{{ hostname }}"
            root_url: "https://{{ hostname }}/grafana/"
            serve_from_sub_path: true

- name: Deploy Kube Prometheus Stack resources
  kubernetes.core.k8s:
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - prometheus/redirect_middleware.yaml
    - prometheus/stripprefix_middleware.yaml
    - prometheus/route.yaml
  vars:
    name: monitoring
    namespace: monitoring
