- name: Deploy loki-stack
  kubernetes.core.helm:
    name: loki-stack
    chart_repo_url: https://grafana.github.io/helm-charts
    chart_ref: loki-stack
    chart_version: 2.8.3
    wait: true
    release_namespace: monitoring
    release_values:
      loki:
        isDefault: false
      
      grafana:
        sidecar:
          datasources:
            enabled: false

- name: Deploy LokiStack resources
  kubernetes.core.k8s:
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - grafana/stripprefix_middleware.yaml
    - grafana/route.yaml
  vars:
    name: monitoring
    namespace: monitoring
