- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: monitoring

- name: Deploy Traefik dashboard
  ansible.builtin.import_tasks: traefik_dashboard.yaml

- name: Deploy Kube Prometheus Stack
  ansible.builtin.import_tasks: kube_prometheus_stack.yaml

- name: Deploy LokiStack
  ansible.builtin.import_tasks: loki_stack.yaml
