- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: monitoring
- name: Deploy kube-prometheus-stack Helm chart
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - kube_prometheus_stack.yaml
    - loki_stack.yaml
    - stripprefix_middleware.yaml
    - traefik_redirect_middleware.yaml
    - prometheus_redirect_middleware.yaml
    - ingress_route.yaml
  vars:
    name: monitoring
    namespace: monitoring
