- name: Enable epel-release
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: latest

- name: Install snapd
  become: true
  ansible.builtin.yum:
    name: snapd
    state: latest
  notify: Reboot

- name: Enable snapd communication socket
  become: true
  ansible.builtin.service:
    name: snapd.socket
    enabled: true
    state: started

- name: Enable classic snap support
  become: true
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
