- name: Enable epel-release
  become: true
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Install snapd
  become: true
  ansible.builtin.package:
    name: snapd
    state: present

- name: Enable snapd communication socket
  become: true
  ansible.builtin.service:
    name: snapd.socket
    enabled: true
    state: started
    daemon_reload: true

- name: Enable classic snap support
  become: true
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: ensure have latest of snap
  become: true
  community.general.snap:
    name: core
  notify: refresh snap core
