apiVersion: v1
kind: Service
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
  labels:
    scrape: "spring-boot"
spec:
  ports:
    - port: {{ app_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ management_port }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app: {{ k8s_name }}