---
argument_specs:
  main:
    options:
      k8s_name:
        type: str
      k8s_namespace:
        type: str
        required: true
      image:
        type: str
        required: true
      app_port:
        type: str
      app_env:
        type: dict
      management_port:
        type: str
      admin_server_name:
        type: str
        required: true
      admin_server_namespace:
        type: str
        required: true
      admin_server_port:
        type: int
        required: true
      