apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
  labels:
    app: "{{ name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ name }}"
  template:
    metadata:
      labels:
        app: "{{ name }}"
      annotations:
        checksum/secret: "{{ secret_checksum }}"  
    spec:
      enableServiceLinks: false
      containers:
        - name: "{{ name }}"
          image: authelia/authelia:4.30.4
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: false
          ports:
            - containerPort: 9091
              name: http
      volumes:
        - name: config
          secret:
            secretName: "{{ name }}"
