apiVersion: v1
kind: Secret
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
stringData:
  configuration.yml: |
    jwt_secret: {{ jwt_secret }}
    server:
      host: 0.0.0.0
      port: 9091
      path: "ssoauth"

    log:
      level: debug
    authentication_backend:
      file:
        path: /config/users_database.yml
    access_control:
      default_policy: deny
      rules:
        - domain: {{ hostname }}
          policy: one_factor

    session:
      secret: {{ session_secret }}
      domain: {{ hostname }}
    # TODO: make this on PVC and backup it
    storage:
      local:
        path: /tmp/db.sqlite3
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /tmp/notification.txt    
  users_database.yml: |
    users:
      admin:
        displayname: Admin
        #{{ admin_password }}
        password: "{{ admin_password_hash }}"
        email: your@email.com
        groups:
          - admins