apiVersion: v1
kind: Secret
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
stringData:
  configuration.yml: |
    regulation:
      max_retries: 3
      find_time: 2m
      ban_time: 5m
    jwt_secret: {{ jwt_secret }}
    server:
      host: 0.0.0.0
      port: {{ app_port }}
      path: {{ path_no_slash }}

    log:
      level: debug
    authentication_backend:
      file:
        path: /config/users_database.yml
      disable_reset_password: true
    access_control:
      default_policy: deny
      rules:
        - domain: {{ hostname }}
          policy: one_factor

    session:
      secret: {{ session_secret }}
      domain: {{ hostname }}
      expiration: 1h
    # TODO: make this on PVC and backup it
    storage:
      local:
        path: /tmp/db.sqlite3
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /tmp/notification.txt    
  users_database.yml: |
    users:
      {{ username }}:
        displayname: {{ username }}
        password: {{ password_hash }}
        email: your@email.com
        groups:
          - admins