apiVersion: v1
kind: Service
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: {{ port }}
  selector:
    app: "{{ name }}"
