---
argument_specs:
  main:
    options:
      auth_middelware_name:
        type: str
        required: true
      auth_middelware_namespace:
        type: str
        required: true
      username:
        type: str
        required: true
      password:
        type: str
        required: true
