- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: cloudflare-tunnel
- name: Get checksums
  ansible.builtin.set_fact:
    secret_checksum: "{{ lookup('ansible.builtin.template', 'secret.yaml') | checksum }}"
    config_map_checksum: "{{ lookup('ansible.builtin.template', 'config-map.yaml') | checksum }}"
  vars:
    name: cloudflared
    namespace: cloudflare-tunnel
- name: Add deployment and service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - config-map.yaml
    - secret.yaml
    - deployment.yaml
  vars:
    name: cloudflared
    namespace: cloudflare-tunnel
- name: Test request using public hostname
  ansible.builtin.uri:
    url: https://{{ public_hostname }}
    return_content: true
  register: this
  until: this.status == 200
  retries: 5
  delay: 1
  failed_when: "'Hello from Ansible Roles Demo Page 2!' not in this.content"
