- name: Set public hostname
  ansible.builtin.set_fact:
    public_hostname: "{{ subdomain }}.{{ public_domainname }}"

- name: Install cloudflared
  ansible.builtin.import_tasks: install_cloudflared_dnf.yaml
  when: ansible_distribution == 'Rocky'

- name: Setup tunnel
  ansible.builtin.import_tasks: setup_tunnel.yaml

- name: Deploy tunnel client
  ansible.builtin.import_tasks: deploy_tunnel_client.yaml

- name: Test request using public hostname
  ansible.builtin.uri:
    url: https://{{ public_hostname }}/ssoauth
    return_content: true
  register: this
  until: this.status == 200
  retries: 5
  delay: 1
  failed_when: "'Login - Authelia' not in this.content"
