- name: Find tunnel credentials file
  ansible.builtin.find:
    paths: ~/.cloudflared
    patterns: "*.json"
  register: matches
- name: Get tunnel credentials
  ansible.builtin.set_fact:
    tunnel_credentials: "{{ matches.files[0].path if matches.matched > 0 else '' }}"
- name: Create cloudflared certificate folder
  ansible.builtin.file:
    path: ~/.cloudflared
    state: directory
    mode: 0770
  when: tunnel_credentials == ''
- name: Create cloudflared certificate
  ansible.builtin.copy:
    dest: ~/.cloudflared/cert.pem
    content: "{{ cloudflare_cert }}"
    mode: 0660
  when: tunnel_credentials == ''
- name: Create tunnel
  ansible.builtin.shell:
    cmd: cloudflared tunnel create {{ tunnel_name }}
  when: tunnel_credentials == ''
- name: Setup tunnel DNS entry
  ansible.builtin.shell:
    cmd: cloudflared tunnel route dns {{ tunnel_name }} {{ public_hostname }}
  when: tunnel_credentials == ''
- name: Remove certificates
  file:
    path: ~/.cloudflared/cert.pem
    state: absent
- name: Find new tunnel credentials file
  ansible.builtin.find:
    paths: ~/.cloudflared
    patterns: "*.json"
  register: matches
- name: Read tunnel credentials
  ansible.builtin.slurp:
    src: "{{ matches.files[0].path }}"
  register: tunnel_credentials_output
- name: Get tunnel credentials content
  ansible.builtin.set_fact:
    tunnel_credentials: "{{ tunnel_credentials_output.content | b64decode | from_json }}"