- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
  delegate_to: localhost
- name: Build an image and push it to DockerHub
  community.docker.docker_image:
    build:
      path: "{{ docker_context_path }}"
    name: "{{ image_name }}"
    repository: "{{ docker_username }}/{{ image_name }}:latest"
    push: true
    source: build
  delegate_to: localhost
- name: Tag image and push it to DockerHub
  community.docker.docker_image:
    name: "{{ image_name }}"
    repository: "{{ docker_username }}/{{ image_name }}:{{ version }}"
    push: true
    source: local
  delegate_to: localhost
