- name: Get new version for {{ tag_prefix }}
  get_version:
    src: "{{ src }}"
    tag_prefix: "{{ tag_prefix }}"
    ignore: "{{ ignore | default(omit) }}"
  delegate_to: localhost
  register: version_result
- name: Register facts. Changed> {{changed}}. Version> {{version}}
  ansible.builtin.set_fact:
    changed: "{{ version_result.changed }}"
    version: "{{ version_result.version }}"
- name: Print new version
  ansible.builtin.debug:
    msg: "Change detected. New version: {{ version }}"
  when: changed
