- name: Update Root user's Password
  become: true
  ansible.builtin.user:
    name: root
    state: present
    password: "{{ root_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
- name: Enable Root SSH Login
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin yes"
    state: present
  notify:
    - Restart ssh
