
- name: Set cluster host
  ansible.builtin.set_fact:
    cluster_host: "{{ ansible_host }}"
- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: ansible-roles
- name: Add deployment and service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - deployment.yaml
    - service.yaml
    - stripprefix_middleware.yaml
    - ingress_route.yaml
  vars:
    name: client
    namespace: ansible-roles
    image: mucsi96/ansible-roles-client:latest
    path: /demo
- name: Get an existing Service object
  kubernetes.core.k8s_info:
    kind: Service
    name: traefik
    namespace: kube-system
  register: load_balancer
- name: Set load balancer ip
  ansible.builtin.set_fact:
    load_balancer_ip: "{{ load_balancer.resources[0].status.loadBalancer.ingress[0].ip }}"
- name: Test a request to the service.
  ansible.builtin.uri:
    url: http://{{ load_balancer_ip }}/demo
    return_content: true
  register: this
  until: this.status == 401
  retries: 5
  delay: 1
  failed_when: "'Hello from Ansible Roles Demo Page 2!' not in this.content"