
- name: Set cluster host
  ansible.builtin.set_fact:
    cluster_host: "{{ ansible_host }}"
- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: ansible-roles
- name: Add deployment and service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - deployment.yaml
    - service.yaml
    - stripprefix_middleware.yaml
    - ingress_route.yaml
  vars:
    name: client
    namespace: ansible-roles
    image: mucsi96/ansible-roles-client:latest
    path: /demo
- name: Authenticate
  ansible.builtin.uri:
    url: https://{{ hostname }}/ssoauth/api/firstfactor
    method: POST
    body_format: json
    body:
      username: "{{ username }}"
      password: "{{ password }}"
  register: auth_resp
  until: auth_resp.status == 200
  retries: 5
  delay: 1
- name: Test a request to the service.
  ansible.builtin.uri:
    url: https://{{ hostname }}/demo
    headers:
      Cookie: "{{ auth_resp.cookies_string }}"
    return_content: true
  register: this
  until: this.status == 200
  retries: 5
  delay: 1
  failed_when: "'Hello from Ansible Roles Demo Page 2!' not in this.content"