apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
data:
  config.yaml: |-
    logDirectory: /var/log/cloudflared
    url: http://traefik.kube-system
    tunnel: {{ tunnel_credentials.TunnelID }}
    credentials-file: /etc/cloudflared/credentials.json
