Kubernetes apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: {{ name }}
  template:
    metadata:
      labels:
        app: {{ name }}
      annotations:
        checksum/secret: {{ secret_checksum }}
        checksum/config-map: {{ config_map_checksum }}
    spec:
      containers:
        - name: {{ name }}
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:2000
            - --config
            - /etc/cloudflared/config.yaml
            - run
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          livenessProbe:
            httpGet:
            # Cloudflared has a /ready endpoint which returns 200 if and only if
            # it has an active connection to the edge.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared/config.yaml
              subPath: config.yaml
            - name: cloudflared-credentials
              mountPath: /etc/cloudflared/credentials.json
              subPath: credentials.json
      volumes:
        - name: cloudflared-config
          configMap:
            name: {{ name }}
            defaultMode: 420
            optional: false
        - name: cloudflared-credentials
          secret:
            secretName: {{ name }}
            defaultMode: 420
            optional: false

