Kubernetes apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ name }}"
  template:
    metadata:
      labels:
        app: "{{ name }}"
    spec:
      containers:
        - name: "{{ name }}"
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - "{{ token }}"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80