apiVersion: v1
kind: Secret
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
stringData:
  credentials.json: >
    {
      "AccountTag": "{{ tunnel_credentials.AccountTag }}",
      "TunnelSecret": "{{ tunnel_credentials.TunnelSecret }}",
      "TunnelID": "{{ tunnel_credentials.TunnelID }}"
    }