apiVersion: v1
kind: Secret
metadata:
  name: "{{ name }}"
  namespace: "{{ namespace }}"
stringData:
  credentials.json: >
    {
      "AccountTag": "{{ cloudflare_account_tag }}",
      "TunnelSecret": "{{ cloudflare_tunnel_secret }}",
      "TunnelID": "{{ cloudflare_tunnel_id }}"
    }