- name: Change root password
  ansible.builtin.import_tasks: root_pwd.yaml

- name: Setup SSH
  ansible.builtin.import_tasks: ssh.yaml

- name: Setup UFW
  ansible.builtin.import_tasks: ufw.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Setup firewalld
  ansible.builtin.import_tasks: firewalld.yaml
  when: ansible_distribution == 'Rocky'

- name: Flush handlers
  meta: flush_handlers
