- name: Build Docker image
  hosts: cluster
  gather_facts: false
  vars_files:
    - ../vars/vault.yaml
  roles:
    - role: build_docker_image
      vars:
        src: "{{ inventory_dir }}/src"
        tag_prefix: "client"
        image_name: "mucsi96/ansible-roles-client"
