- name: Build Docker images
  hosts: cluster
  gather_facts: false
  vars_files:
    - ../vars/vault.yaml
  roles:
    - name: Build client image
      role: build_docker_image
      vars:
        src: "{{ inventory_dir }}/demo_app/client/src"
        docker_context_path: "{{ inventory_dir }}/demo_app/client"
        tag_prefix: "demo-app-client"
        image_name: "mucsi96/ansible-roles-demo-app-client"
    - name: Build server image
      role: build_docker_image
      vars:
        src: "{{ inventory_dir }}/demo_app/server/src"
        docker_context_path: "{{ inventory_dir }}/demo_app/server"
        tag_prefix: "demo-app-server"
        image_name: "mucsi96/ansible-roles-demo-app-server"
    - name: Build spring-boot-admin image
      role: build_docker_image
      vars:
        src: "{{ inventory_dir }}/spring-boot-admin/src"
        docker_context_path: "{{ inventory_dir }}/spring-boot-admin"
        tag_prefix: "spring-boot-admin"
        image_name: "mucsi96/ansible-roles-spring-boot-admin"
