- name: Deploy Kubernetes demo
  hosts: cluster
  gather_facts: false
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  tasks:
    - name: Deploy db
      ansible.builtin.include_role:
        name: deploy_postgres_db
    - name: Deploy server
      ansible.builtin.include_role:
        name: deploy_spring_app
      vars:
        image: mucsi96/ansible-roles-demo-app-server:3
        base_path: /demo/api
        app_env:
          POSTGRES_DB: "{{ db_name }}"
          POSTGRES_HOSTNAME: "{{ db_host }}"
          POSTGRES_PORT: "{{ db_port }}"
          POSTGRES_USER: "{{ db_username }}"
          POSTGRES_PASSWORD: "{{ db_password }}"
          MESSAGE: Hello from Ansible Roles Spring Demo!
    - name: Deploy client
      ansible.builtin.include_role:
        name: deploy_client_app
      vars:
        image: mucsi96/ansible-roles-demo-app-client:3
        base_path: /demo
    - name: Authenticate
      ansible.builtin.uri:
        url: https://{{ hostname }}/ssoauth/api/firstfactor
        method: POST
        body_format: json
        body:
          username: "{{ username }}"
          password: "{{ password }}"
      register: auth_resp
      until: auth_resp.status == 200
      retries: 5
      delay: 1
    - name: Test a request to the service.
      ansible.builtin.uri:
        url: https://{{ hostname }}/demo
        headers:
          Cookie: "{{ auth_resp.cookies_string }}"
        return_content: true
      register: this
      until: this.status == 200
      retries: 5
      delay: 1
      failed_when: "'Hello from Ansible Roles Spring Demo!' not in this.content"
