- name: Deploy Kubernetes demo
  hosts: cluster
  gather_facts: false
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  tasks:
    - name: Deploy db
      ansible.builtin.include_role:
        name: deploy_postgres_db
    - name: Deploy server
      ansible.builtin.include_role:
        name: deploy_spring_app
      vars:
        image: mucsi96/ansible-roles-demo-app-server:3
        base_path: /demo/api
        app_env:
          POSTGRES_DB: "{{ db_name }}"
          POSTGRES_HOSTNAME: "{{ db_host }}"
          POSTGRES_PORT: "{{ db_port }}"
          POSTGRES_USER: "{{ db_username }}"
          POSTGRES_PASSWORD: "{{ db_password }}"
          MESSAGE: Hello from Ansible Roles Spring Demo!
    - name: Deploy client
      ansible.builtin.include_role:
        name: deploy_client_app
      vars:
        image: mucsi96/ansible-roles-demo-app-client:3
        base_path: /demo
    - name: Test
      ansible.builtin.script:
        cmd: ../demo_app/test.py
      environment:
        HOSTNAME: "{{ hostname }}"
        USERNAME: "{{ username }}"
        PASSWORD: "{{ password }}"
      delegate_to: localhost
      changed_when: false
