- name: Deploy Cloudflare tunnel
  hosts: cluster
  vars_files:
    - ../vars/vault.yaml
  roles:
    - role: deploy_cloudflare_tunnel
      vars:
        subdomain: ansible-roles-demo
        tunnel_name: ansible-roles-demo
