- name: Deploy Cloudflare tunnel
  hosts: cluster
  vars_files:
    - ../vars/vault.yaml
  roles:
    - role: deploy_cloudflare_tunnel
      vars:
        subdomain: "{{ 'ansible-roles' if ci != 'true' else 'ansible-roles-ci' }}"
        tunnel_name: "{{ 'ansible-roles' if ci != 'true' else 'ansible-roles-ci' }}"
