- name: Deploy Cloudflare tunnel
  hosts: cluster
  vars_files:
    - ../vars/vault.yaml
  roles:
    - role: deploy_cloudflare_tunnel
      vars:
        subdomain: "{{ subdomain | default('ansible-roles') }}"
        tunnel_name: "{{ subdomain | default('ansible-roles') }}"
