- name: Deploy Kubernetes demo
  hosts: cluster
  gather_facts: false
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  roles:
    - role: deploy_postgres_db
    - role: deploy_kubernetes_demo
      vars:
        hostname: "{{ subdomain }}.{{ public_domainname }}"
