- name: Deploy Kubernetes monitoring stack
  hosts: cluster
  gather_facts: false
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  tasks:
    - name: Deploy K8S monitoring
      ansible.builtin.include_role:
        name: deploy_kubenetes_monitoring
    - name: Test
      ansible.builtin.script:
        cmd: "{{ inventory_dir }}/tests/{{ item }}"
        chdir: "{{ inventory_dir }}/tests"
      environment:
        HOSTNAME: "{{ hostname }}"
        USERNAME: "{{ username }}"
        PASSWORD: "{{ password }}"
      delegate_to: localhost
      changed_when: false
      with_items:
        - dashboard.py
        - traefik.py
        - prometheus.py
        - grafana.py
        - grafana_traefik.py
        - grafana_jvm.py
