- name: Deploy Kubernetes monitoring stack
  hosts: cluster
  gather_facts: false
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  tasks:
    - name: Deploy K8S monitoring
      ansible.builtin.include_role:
        name: deploy_kubenetes_monitoring
    - name: Test Prometheus
      ansible.builtin.script:
        cmd: "{{ inventory_dir }}/tests/prometheus.py"
        chdir: "{{ inventory_dir }}/tests"
      environment:
        HOSTNAME: "{{ hostname }}"
        USERNAME: "{{ username }}"
        PASSWORD: "{{ password }}"
      delegate_to: localhost
      changed_when: false
    - name: Test Grafana
      ansible.builtin.script:
        cmd: "{{ inventory_dir }}/tests/grafana.py"
        chdir: "{{ inventory_dir }}/tests"
      environment:
        HOSTNAME: "{{ hostname }}"
        USERNAME: "{{ username }}"
        PASSWORD: "{{ password }}"
      delegate_to: localhost
      changed_when: false
