- name: Create new SSH
  hosts: cluster
  roles:
    - role: new-ssh-user
      vars:
        username: deploy
        private_key_file: "{{ inventory_dir }}/.ssh/id_ed25519"
        ansible_user: root
        ansible_ssh_pass: "123"
        ansible_port: 22
