name: CI

on:
  push:
    branches:
      - main

jobs:
  build-client-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: ansible-playbook playbooks/build_docker_image.yaml --extra-vars "docker_username=${{ secrets.DOCKER_USERNAME }} docker_password=${{ secrets.DOCKER_PASSWORD }}"

  local-ansible-deploy:
    runs-on: macos-12
    needs: build-client-image
    steps:
      - uses: actions/checkout@v3

      - name: Cache Python requirements
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/pip
          key: 1-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            1-${{ runner.os }}-pip-

      - name: Install Ansible
        run: brew install hudochenkov/sshpass/sshpass ansible

      - name: Show Ansible version
        run: ansible-playbook --version

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: Provision
        run: ansible-playbook playbooks/enable_root_login.yaml playbooks/new_ssh_user.yaml playbooks/ssh_hardening.yaml playbooks/update_packages.yaml playbooks/install_kubernetes.yaml
