---
argument_specs:
  main:
    options:
      hostname:
        type: str
        required: true
      auth_middelware_name:
        type: str
        required: true
      username:
        type: str
        required: true
      password:
        type: str
        required: true
